# Backbone
backbone: mlnn

# Transfer loss related
transfer_loss_weight: 20.0
regression_loss_weight: 5.0
transfer_loss: adv

# Optimizer related
weight_decay: 0.001
lr: 0.04

lr_scheduler: True
lr_gamma: 0.001 # 1/n_epoch*10
lr_decay: 0.75
momentum: 0.9

# Training related
n_iter_per_epoch: 500 # not use, since using batch
n_epoch: 100
early_stopping_patience: 10

# Others
seed: 1
num_workers: 3

# bottleneck
use_bottleneck: False

#ata_dir: '/media/sun/DATA/drop_landing_workspace/data'
data_dir: "${DATA_PATH}"

src_domain: "None"
tcl_domain: "None" 
tre_domain: "None" 
tst_domain: "repeated_5trials_5subjects_kam_norm_landing_data.hdf5" 

config_name: dann
config_comments: 'complex output layers and using repeated IMU'

