# Backbone
backbone: mlnn

# transfer loss function
transfer_loss: adv

# Optimizer related, L2 norm
weight_decay: 0.001

# lr:0.04
lr: 0.05
lr_scheduler: True
lr_gamma: 0.001 # lr/(1.0 + lr_gamma * n_epoch)^lr_decay
lr_decay: 0.7
momentum: 0.9

# Training related
n_iter_per_epoch: 500 # not use, since using batch
n_epoch: 1000
early_stopping_patience: 20

# Others
seed: 1
num_dataloader_workers: 5

# bottleneck
use_bottleneck: False

#ata_dir: '/media/sun/DATA/drop_landing_workspace/data'
data_dir: "${DATA_PATH}"

src_domain: "None"
tcl_domain: "None" 
tre_domain: "None" 
tst_domain:  "None" 

config_name: "dann"
config_comments: 'complex output layers and using repeated IMU'
model_name: "mlnn"
