# Backbone
backbone: mlnn

# Transfer loss related
transfer_loss_weight: 1.2
regression_loss_weight: 1.0
transfer_loss: None

# Optimizer related
weight_decay: 5e-2
lr: 0.01
lr_scheduler: False
lr_gamma: 0.001
lr_decay: 0.75

# Training related
n_iter_per_epoch: 800
n_epoch: 100
early_stopping_patience: 10

# Others
seed: 1
num_workers: 3

# bottleneck
use_bottleneck: False

data_dir: '/media/sun/DATA/drop_landing_workspace/data/'

src_domain: "kam_norm_walking_data.hdf5"
tgt_domain: "repeated_kam_norm_landing_data.hdf5" 

labels_name:
  - 'R_KNEE_MOMENT_X'

config_alias_name: imu augmentation
config_comments: 'complex output layers and using repeated IMU'
